name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        edition: [full, lite]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install and build
        env:
          APP_EDITION: ${{ matrix.edition }}
        run: |
          npm install
          npm run postinstall
          if [ "${{ matrix.edition }}" = "lite" ]; then
            npm run build:lite
          else
            npm run build
          fi
        shell: bash

      - name: Publish releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_EDITION: ${{ matrix.edition }}
        run: |
          if [ "${{ matrix.edition }}" = "lite" ]; then
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              npm exec electron-builder -- --publish always --win -c.productName="Evos-Launcher-Lite" -c.appId="baby.addalyn.evoslauncher.lite" -c.publish.channel="lite"
            else
              npm exec electron-builder -- --publish always --linux -c.productName="Evos-Launcher-Lite" -c.appId="baby.addalyn.evoslauncher.lite" -c.publish.channel="lite"
            fi
          else
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              npm exec electron-builder -- --publish always --win
            else
              npm exec electron-builder -- --publish always --linux
            fi
          fi
        shell: bash
